// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Set(arg1, arg2) {
  return window['go']['store']['Store']['Set'](arg1, arg2);
}
